using System.IO;

namespace UnityEngine.TestTools.Graphics.Shaders
{
    /// <summary>
    /// Handle to a loaded shader
    /// </summary>
    public readonly struct ShaderHandle
    {
        /// <summary>
        /// The name of the shader
        /// </summary>
        public readonly string name;

        /// <summary>
        /// The path to the shader file
        /// </summary>
        public readonly string path;

        /// <summary>
        /// The path relative to the project
        /// </summary>
        public readonly string relativePath;

        /// <summary>
        /// The type of the shader
        /// </summary>
        public readonly ShaderType type;

        /// <summary>
        /// True if the shader was generated by the test framework
        /// </summary>
        public readonly bool isGenerated;

        /// <summary>
        /// Creates a new ShaderHandle instance
        /// </summary>
        /// <param name="path">
        /// The path to the shader file
        /// </param>
        /// <param name="type">
        /// The type of the shader
        /// </param>
        /// <param name="relativePath">
        /// The path relative to the project
        /// </param>
        /// <param name="isGenerated">
        /// True if the shader was generated by the test framework
        /// </param>
        public ShaderHandle(string path, ShaderType type, string relativePath = null, bool isGenerated = false)
        {
            this.name = Path.GetFileNameWithoutExtension(path);
            this.path = path;
            this.relativePath = relativePath ?? path;
            this.type = type;
            this.isGenerated = isGenerated;
        }
    }
}
