using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
#if UNITY_TEST_PROTOCOL
using Unity.TestProtocol;
using Unity.TestProtocol.Messages;
#endif

namespace UnityEngine.TestTools.Graphics
{
    /// <summary>
    /// Abstracts file I/O for <see cref="ShaderWarningCollector"/> to enable testing without disk access.
    /// </summary>
    internal interface IWarningsFileWriter
    {
        /// <summary>
        /// Writes warnings to disk and returns the full path of the written file.
        /// </summary>
        string Write(string outputDir, string fileName, IReadOnlyList<string> warnings);
    }

    /// <summary>
    /// Default implementation that writes to the real file system and publishes a UTP artifact.
    /// </summary>
    internal class DiskWarningsFileWriter : IWarningsFileWriter
    {
        public string Write(string outputDir, string fileName, IReadOnlyList<string> warnings)
        {
            if (!Directory.Exists(outputDir))
                Directory.CreateDirectory(outputDir);

            var filePath = Path.Combine(outputDir, fileName);

            var sb = new StringBuilder();
            sb.AppendLine($"# Shader Warnings ({warnings.Count} unique warning(s) detected)");
            sb.AppendLine("# Generated by Graphics Test Framework");
            foreach (var warning in warnings)
                sb.AppendLine(warning);

            File.WriteAllText(filePath, sb.ToString());
            GraphicsTestLogger.Log(LogType.Log, $"ShaderWarningCollector: wrote warnings to {filePath}");

            var fullPath = Path.GetFullPath(filePath);
#if UNITY_TEST_PROTOCOL
            var message = ArtifactPublishMessage.Create(fullPath);
            GraphicsTestLogger.Log(LogType.Log, $"ShaderWarningCollector: publishing artifact {fullPath}");
            Debug.Log(UnityTestProtocolMessageBuilder.Serialize(message));
#else 
            GraphicsTestLogger.DebugWarning($"ShaderWarningCollector: Artifact publishing requires com.unity.external.test-protocol. Please install the package to enable this feature. Received artifact path: {fullPath}");
#endif

            return filePath;
        }
    }

    /// <summary>
    /// Collects shader warnings from the Unity log during builds and test runs.
    /// When enabled via <c>-shader-warnings-as-errors</c>, captured warnings are written
    /// to a <c>ShaderWarnings.log</c> artifact and can be used to fail the job.
    /// </summary>
    public static class ShaderWarningCollector
    {
        const string k_OutputFileName = "ShaderWarnings.log";
        const string k_ShaderWarningsOutputDir = "Logs";

        /// <summary>
        /// The file path where collected warnings will be written when <see cref="StopAndReport"/> is called.
        /// </summary>
        public static string OutputFilePath { get; set; } = Path.Combine(k_ShaderWarningsOutputDir, k_OutputFileName);

        internal static IWarningsFileWriter FileWriter { get; set; } = new DiskWarningsFileWriter();

        static readonly Regex k_ShaderWarningRegex = new(
            "^Shader warning in '(?<shaderName>[^']+)': (?<message>.+)",
            RegexOptions.Compiled,
            TimeSpan.FromMilliseconds(100)
        );

        static readonly ConcurrentBag<string> k_Warnings = new();
        static volatile bool s_IsCollecting;

        /// <summary>
        /// Whether the collector is currently listening for shader warnings.
        /// </summary>
        public static bool IsCollecting => s_IsCollecting;

        /// <summary>
        /// Whether any shader warnings have been collected.
        /// </summary>
        public static bool HasWarnings => !k_Warnings.IsEmpty;

        /// <summary>
        /// The deduplicated, sorted list of collected warnings. Only valid after <see cref="StopAndReport"/>.
        /// </summary>
        public static IReadOnlyList<string> CollectedWarnings => GetDeduplicatedWarnings();

        /// <summary>
        /// Starts listening for shader warnings on <see cref="Application.logMessageReceivedThreaded"/>.
        /// Clears any previously collected warnings.
        /// </summary>
        public static void StartCollecting()
        {
            ClearInternal();
            s_IsCollecting = true;
            Application.logMessageReceivedThreaded += OnLogMessageReceived;
            GraphicsTestLogger.Log(LogType.Log, "ShaderWarningCollector: started collecting shader warnings.");
        }

        /// <summary>
        /// Stops listening, writes collected warnings to a file, and publishes the file as a test artifact.
        /// </summary>
        public static void StopAndReport()
        {
            Application.logMessageReceivedThreaded -= OnLogMessageReceived;
            s_IsCollecting = false;

            var warnings = GetDeduplicatedWarnings();
            if (warnings.Count == 0)
            {
                GraphicsTestLogger.Log(LogType.Log, "ShaderWarningCollector: no shader warnings detected.");
                return;
            }

            GraphicsTestLogger.Log(
                LogType.Warning,
                $"ShaderWarningCollector: {warnings.Count} unique shader warning(s) detected."
            );

            FileWriter.Write(Path.GetDirectoryName(OutputFilePath), Path.GetFileName(OutputFilePath), warnings);
        }

        /// <summary>
        /// Returns true if the given log message is a shader warning.
        /// </summary>
        internal static bool IsShaderWarning(string message)
        {
            if (string.IsNullOrEmpty(message))
                return false;

            try
            {
                return k_ShaderWarningRegex.IsMatch(message);
            }
            catch (RegexMatchTimeoutException)
            {
                return message.StartsWith("Shader warning in ", StringComparison.Ordinal);
            }
        }

        internal static void ClearInternal()
        {
            while (k_Warnings.TryTake(out _)) { }
        }

        /// <summary>
        /// Injects a warning directly into the collector. For testing only.
        /// </summary>
        internal static void InjectWarning(string warning)
        {
            k_Warnings.Add(warning);
        }

        static void OnLogMessageReceived(string logString, string stackTrace, LogType type)
        {
            if (type == LogType.Warning && IsShaderWarning(logString))
                k_Warnings.Add(logString);
        }

        static List<string> GetDeduplicatedWarnings()
        {
            var set = new HashSet<string>(StringComparer.Ordinal);
            foreach (var w in k_Warnings)
                set.Add(w);

            var sorted = new List<string>(set);
            sorted.Sort(StringComparer.Ordinal);
            return sorted;
        }

    }
}
